### ISSUE TITLE
Looks like types are not being included

### ISSUE THREAD

**Issue by christopher-caldwell** [craigmichaelmartin/fawait#16]
The package json has a `"types"` field, but it also has a `"files"` field. I _think_ this is excluding the types from being included.

I can 100% confirm that `npm i --save fawait` **does not** include types and TS is showing an error.

I think the file is to simply add the `.d.ts` to the `"files"` key array

**Comment by craigmichaelmartin** [comment]
Good catch, @christopher-caldwell! Thanks so much for pointing it out. Release `2.3.0` has the fix!
